<?php
require '../../../../../libraries/fpdf186/fpdf.php';
require '../../../../../model/admin/adminResidentModel.php';
require '../../PDFExportDesign.php';
session_start();
ob_start();

// Extend FPDF class to add headers and footers
class PDFWithHeaderFooter extends FPDF {
    private $tableHeaders;
    private $startX;

    function Header() {
        // Logos
        $this->Image('../../../../../img/Barangay Logo.png', 75, 5, 20);
        $this->Image('../../../../../img/lunsgodNgMayNilaLogo.png', 203, 5, 20);

        // Title
        $this->SetFont('Arial', 'B', 16);
        $this->Cell(0, 10, 'TODAY\'S REPORTED BLOTTERS LIST', 0, 1, 'C');

        $this->SetFont('Arial', '', 10);
        $this->Cell(0, 6, 'Generated on: ' . date('F j, Y'), 0, 1, 'C');
        $this->Cell(0, 6, 'Generated by: ' . htmlspecialchars($_SESSION['last_name']) . ', ' . htmlspecialchars($_SESSION['first_name']), 0, 1, 'C');
        $this->Cell(0, 6, 'New Blotters: ' . $GLOBALS['totalRequestsToday'], 0, 1, 'C');
        $this->Ln(8);

        // Table Header
        $this->drawTableHeader();
    }

    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'Page ' . $this->PageNo() . '/{nb}', 0, 0, 'C');
        $this->Line(10, $this->GetY()-2, $this->GetPageWidth()-10, $this->GetY()-2);
    }

    function setTableHeaders($headers, $startX) {
        $this->tableHeaders = $headers;
        $this->startX = $startX;
    }

    function drawTableHeader() {
        $this->SetFont('Arial', 'B', 8);
        $this->SetFillColor(64, 64, 64);
        $this->SetTextColor(255);
        $this->SetX($this->startX);
        $maxHeight = 10;
        $paddingTop = 2;
    
        foreach ($this->tableHeaders as $header) {
            $x = $this->GetX();
            $y = $this->GetY();
            $this->Rect($x, $y, $header['width'], $maxHeight, 'DF');
            $this->SetXY($x, $y + $paddingTop);
    
            // Use MultiCell instead of Cell to wrap text
            $this->MultiCell($header['width'], 4, $header['title'], 0, 'C', false);
            
            $this->SetXY($x + $header['width'], $y);
        }
    
        $this->Ln($maxHeight);
    }
    
}

// Fetch account data
$adminResidentModel = new AdminResidentModel();
$reports = $adminResidentModel->GETblottersReportedToday($conn, 0, 0); // Get data for today (no pagination needed here)
$GLOBALS['totalRequestsToday'] = is_array($reports) ? count($reports) : 0; // Safe count
$conn->close();

// Setup headers
$headers = [
    ['width' => 15, 'title' => 'Case Number'],
    ['width' => 20, 'title' => 'Complainant'],
    ['width' => 20, 'title' => 'Complainant Type'],
    ['width' => 25, 'title' => 'Subject'],
    ['width' => 20, 'title' => 'Official'],
    ['width' => 17, 'title' => 'Date of Incident'],
    ['width' => 15, 'title' => 'Time of Incident'],
    ['width' => 25, 'title' => 'Location'],
    ['width' => 20, 'title' => 'Respondent'],
    ['width' => 45, 'title' => 'Narration'],
    ['width' => 20, 'title' => 'Evidence Description'],
    ['width' => 15, 'title' => 'Remarks'],
    ['width' => 15, 'title' => 'Status'],
    ['width' => 20, 'title' => 'Date Submitted']
];

$totalWidth = array_sum(array_column($headers, 'width'));
$pdf = new PDFWithHeaderFooter('L', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->SetAutoPageBreak(true, 25);
$pageWidth = $pdf->GetPageWidth();
$startX = ($pageWidth - $totalWidth) / 2;
$pdf->setTableHeaders($headers, $startX);
$pdf->AddPage();

// Render table
$pdf->SetFont('Arial', '', 8);
$pdf->SetTextColor(0);
$fill = false;
foreach ($reports as $report) {
    if ($pdf->GetY() > 170) {
        $pdf->AddPage();
        $fill = false;
    }

    $pdf->SetX($startX);
    $cells = [
        $report['Case_number'] ?? 'N/A',
        $report['complainant'] ?? 'N/A',
        $report['complainant_type'] ?? 'N/A',
        $report['subject'] ?? 'N/A',
        $report['official_name'] ?? 'N/A',
        $report['date_of_incident'] ?? 'N/A',
        $report['time_of_incident'] ?? 'N/A',
        $report['location'] ?? 'N/A',
        $report['Respondent'] ?? 'N/A',
        $report['narration'] ?? 'N/A',
        $report['evidence_description'] ?? 'N/A',
        $report['remarks'] ?? 'N/A',
        $report['status'] ?? 'N/A',
        $report['date_submitted'] ?? 'N/A'
    ];

    $maxHeight = 6;
    foreach ($cells as $i => $content) {
        $numLines = $pdf->GetStringWidth($content) > 0 ? ceil($pdf->GetStringWidth($content) / $headers[$i]['width']) : 1;
        $maxHeight = max($maxHeight, $numLines * 8);
    }

    foreach ($headers as $i => $header) {
        $x = $pdf->GetX();
        $y = $pdf->GetY();
    
        $pdf->SetFillColor($fill ? 240 : 255);
        $pdf->Rect($x, $y, $header['width'], $maxHeight, 'F');
        if (in_array($i, [0,1,2,3,4,5,6,7,8,9,10,11,12,13])) {
            // Save position
            $pdf->SetXY($x, $y);
        
            // Calculate number of lines the MultiCell will take
            $lineCount = ceil($pdf->GetStringWidth($cells[$i]) / $header['width']);
            $lineHeight = 3.5;
            $cellHeight = $lineCount * $lineHeight;
        
            // Calculate vertical padding to center the text
            $yOffset = ($maxHeight - $cellHeight) / 2;
            $pdf->SetXY($x, $y + $yOffset);
        
            // Draw the text
            $pdf->MultiCell($header['width'], $lineHeight, $cells[$i], 0, 'C', false);
        
            // Reset X to next cell (Y already reset)
            $pdf->SetXY($x + $header['width'], $y);
        }
        
    
        $pdf->Rect($x, $y, $header['width'], $maxHeight);
    }
    

    $pdf->Ln($maxHeight);
    $fill = !$fill;
}


ob_end_clean();
// Output with more appropriate filename
$pdf->Output('Blotters_Reported_Today_PDF_Export' . date('Y-m-d') . '.pdf', 'I');
?>
