<?php
require '../../../../../libraries/fpdf186/fpdf.php';
require '../../../../../model/admin/adminResidentModel.php';
require '../../PDFExportDesign.php';
session_start();

// Extend FPDF class to add headers and footers
class PDFWithHeaderFooter extends FPDF {
    private $tableHeaders;
    private $startX;

    function Header() {
        // Logos
        $this->Image('../../../../../img/Barangay Logo.png', 78, 5, 20);
        $this->Image('../../../../../img/lunsgodNgMayNilaLogo.png', 200, 5, 20);

        // Title
        $this->SetFont('Arial', 'B', 16);
        $this->Cell(0, 10, 'TODAY\'S REQUESTED PERMITS LIST', 0, 1, 'C');

        $this->SetFont('Arial', '', 10);
        $this->Cell(0, 6, 'Generated on: ' . date('F j, Y'), 0, 1, 'C');
        $this->Cell(0, 6, 'Generated by: ' . htmlspecialchars($_SESSION['last_name']) . ', ' . htmlspecialchars($_SESSION['first_name']), 0, 1, 'C');
        $this->Cell(0, 6, 'New Permits: ' . $GLOBALS['totalNewPermit'], 0, 1, 'C');
        $this->Ln(8);

        // Table Header
        $this->drawTableHeader();
    }

    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'Page ' . $this->PageNo() . '/{nb}', 0, 0, 'C');
        $this->Line(10, $this->GetY()-2, $this->GetPageWidth()-10, $this->GetY()-2);
    }

    function setTableHeaders($headers, $startX) {
        $this->tableHeaders = $headers;
        $this->startX = $startX;
    }

    function drawTableHeader() {
        $this->SetFont('Arial', 'B', 8);
        $this->SetFillColor(64, 64, 64);
        $this->SetTextColor(255);
        $this->SetX($this->startX);
        $maxHeight = 10;
        $paddingTop = 2;
    
        foreach ($this->tableHeaders as $header) {
            $x = $this->GetX();
            $y = $this->GetY();
            $this->Rect($x, $y, $header['width'], $maxHeight, 'DF');
            $this->SetXY($x, $y + $paddingTop);
    
            // Use MultiCell instead of Cell to wrap text
            $this->MultiCell($header['width'], 4, $header['title'], 0, 'C', false);
            
            $this->SetXY($x + $header['width'], $y);
        }
    
        $this->Ln($maxHeight);
    }
    
}

// Fetch account data
$adminResidentModel = new AdminResidentModel();
$requests = $adminResidentModel->GETnewPermitsToday($conn, 0, 0); // Get data for today (no pagination needed here)
$GLOBALS['totalNewPermit'] = is_array($requests) ? count($requests) : 0; // Safe count
$conn->close();

// Setup headers
$headers = [
    ['width' => 15, 'title' => 'Request ID'],
    ['width' => 30, 'title' => 'Type of Document'],
    ['width' => 30, 'title' => 'Requestor'],
    ['width' => 50, 'title' => 'Purpose'],
    ['width' => 25, 'title' => 'Date Submitted'],
    ['width' => 25, 'title' => 'Last Updated'],
    ['width' => 25, 'title' => 'Type of Payment'],
    ['width' => 15, 'title' => 'Payment Amount'],
    ['width' => 15, 'title' => 'No. Of Copies'],
    ['width' => 15, 'title' => 'Status']
];

$totalWidth = array_sum(array_column($headers, 'width'));
$pdf = new PDFWithHeaderFooter('L', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->SetAutoPageBreak(true, 25);
$pageWidth = $pdf->GetPageWidth();
$startX = ($pageWidth - $totalWidth) / 2;
$pdf->setTableHeaders($headers, $startX);
$pdf->AddPage();

// Render table
$pdf->SetFont('Arial', '', 8);
$pdf->SetTextColor(0);
$fill = false;

foreach ($requests as $request) {
    if ($pdf->GetY() > 170) {
        $pdf->AddPage();
        $fill = false;
    }

    $pdf->SetX($startX);
    $cells = [
        $request['request_id'] ?? 'N/A',
        $request['template_name'] ?? 'N/A',       // Changed from type_of_document
        $request['full_name'] ?? 'N/A',      // Changed from Requestor
        $request['purpose'] ?? 'N/A',
        $request['date_submitted'] ?? 'N/A',      // Changed from account_id
        $request['last_updated'] ?? 'N/A',        // Changed from account_id
        $request['payment_name'] ?? 'N/A',        // Changed from account_id
        $request['payment_amount'] ?? 'N/A',      // Changed from account_id
        $request['number_of_copies'] ?? 'N/A',        // Changed from account_id
        $request['status'] ?? 'N/A'               // Changed from account_id
    ];

    $maxHeight = 6;
    foreach ($cells as $i => $content) {
        $numLines = $pdf->GetStringWidth($content) > 0 ? ceil($pdf->GetStringWidth($content) / $headers[$i]['width']) : 1;
        $maxHeight = max($maxHeight, $numLines * 4);
    }

    foreach ($headers as $i => $header) {
        $x = $pdf->GetX();
        $y = $pdf->GetY();

        $pdf->SetFillColor($fill ? 240 : 255);
        $pdf->Rect($x, $y, $header['width'], $maxHeight, 'F');

        $pdf->SetXY($x, $y + 2);
        $pdf->MultiCell($header['width'], 4, $cells[$i], 0, 'C', false);
        $pdf->SetXY($x + $header['width'], $y);
        $pdf->Rect($x, $y, $header['width'], $maxHeight);
    }

    $pdf->Ln($maxHeight);
    $fill = !$fill;
}

// Output with more appropriate filename
$pdf->Output('New_Permits_Today_PDF_Export_('.date('m-d-Y').').pdf', 'I');
?>
